function [subject,reference,protocol,baselineStart,baselineEnd,interventionStart,interventionEnd,wakeTime,bedTime,chronotype] = importindex2(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   [subject,reference,protocol,baselineStart,baselineEnd,interventionStart,interventionEnd,wakeTime,bedTime,chronotype]
%   = IMPORTFILE1(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as
%   column vectors.
%
%   [subject,reference,protocol,baselineStart,baselineEnd,interventionStart,interventionEnd,wakeTime,bedTime,chronotype]
%   = IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   [subject,reference,protocol,baselineStart,baselineEnd,interventionStart,interventionEnd,wakeTime,bedTime,chronotype]
%   = IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [subject,reference,protocol,baselineStart,baselineEnd,interventionStart,interventionEnd,wakeTime,bedTime,chronotype]
%   = importfile1('index.xlsx','Sheet1',2,47);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/06/23 11:34:28

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 47;
end

%% Import the data, extracting spreadsheet dates in Excel serial date format
[~, ~, raw, dates] = xlsread(workbookFile, sheetName, sprintf('A%d:J%d',startRow(1),endRow(1)),'' , @convertSpreadsheetExcelDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:J%d',startRow(block),endRow(block)),'' , @convertSpreadsheetExcelDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dates = [dates;tmpDateNumBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,3,10]);
raw = raw(:,[1,8,9]);
dates = dates(:,[4,5,6,7]);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
subject = data(:,1);
reference = cellVectors(:,1);
protocol = cellVectors(:,2);
dates(~cellfun(@(x) isnumeric(x) || islogical(x), dates)) = {NaN};
baselineStart = datetime([dates{:,1}].', 'ConvertFrom', 'Excel');
baselineEnd = datetime([dates{:,2}].', 'ConvertFrom', 'Excel');
interventionStart = datetime([dates{:,3}].', 'ConvertFrom', 'Excel');
interventionEnd = datetime([dates{:,4}].', 'ConvertFrom', 'Excel');
wakeTime = data(:,2);
bedTime = data(:,3);
chronotype = cellVectors(:,3);

